# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: LutheringLavesLauncher Packing

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    container:
      image: python:3.10-slim

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nuitka
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Packing
        run: |
          python packing.py
