# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: LutheringLavesLauncher Packing

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    container:
      image: moonbuggy2000/nuitka:py3.13-debian 

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Packing
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python packing.py
