# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: LutheringLavesLauncher Packing

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    container:
      image: lastlive/nuitka-patchelf

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: show dependencies
        run: |
          nuitka --version

      - name: Packing
        run: |
          python -m nuitka --standalone --python-flag="-S" --follow-imports \
          --windows-console-mode="disable"  --windows-icon-from-ico="resource/launcher.ico" \
          --main="LutheringLavesLauncher.py"  --enable-plugins="pyside6"  --linux-icon="resource/launcher.ico" \
          --include-raw-dir=tools=tools   --include-raw-dir=Font=Font   --include-raw-dir=resource=resource

      - name: Get current time
        id: current-time
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Compress LutheringLavesLauncher.dist
        run: |
          tar -czf "LutheringLavesLauncher_${{ env.timestamp }}.zip" LutheringLavesLauncher.dist/

      - name: Upload zip to WebDAV
        uses: XPH0816/webdav-deploy-action@v0.3
        with:
          url: ${{ secrets.WEB_DAV_URL }}
          username: ${{ secrets.WEB_DAV_USERNAME }}
          password: ${{ secrets.WEB_DAV_PASSWORD }}
          local: "LutheringLavesLauncher_${{ env.timestamp }}.zip"
          remote: "space2/LLL-release/"
          method: "copy"

      - name: Clean up
        run: |
          rm "LutheringLavesLauncher_${{ env.timestamp }}.zip"
          rm -rf LutheringLavesLauncher.dist/
          rm -rf LutheringLavesLauncher.build/